#PBS -S /bin/csh
#PBS -N cfd

#PBS -q low
#PBS -l select=1:ncpus=2:model=san
#PBS -l walltime=4:00:00
#PBS -j oe
#PBS -m e
#PBS -o bringleout.txt
cd $PBS_O_WORKDIR
. ${MODULESHOME}/init/bash

cmdfn=${PBS_JOBID}.$end

for i in $(ls -d 3d*| head -n $end | tail -n $num); do
  echo "tar xvzf $i -C ../" >>$cmdfn
  #j=$(ls -l $i | sed 's/\(.*\)->\ \(.*\)/\2/')
  #echo "tar cvzf tar/$i.tgz $j" >>$cmdfn
done
  
xargs -d '\n' -I cmd -P 32 bash -c 'cmd' < $cmdfn

rm $cmdfn
