#!/bin/bash
#PBS -j oe
#PBS -l nodes=1:ppn=32:xe
#PBS -q low
#PBS -l walltime=10:00:00

cd $PBS_O_WORKDIR
. ${MODULESHOME}/init/bash

cmdfn=${PBS_JOBID}.$end

for i in $(ls -d 3d*| head -n $end | tail -n $num); do
  echo "tar xvzf $i -C ../" >>$cmdfn
  #j=$(ls -l $i | sed 's/\(.*\)->\ \(.*\)/\2/')
  #echo "tar cvzf tar/$i.tgz $j" >>$cmdfn
done
  
aprun -n 1 -N 1 -d 32 xargs -d '\n' -I cmd -P 32 bash -c 'cmd' < $cmdfn

rm $cmdfn
