import numpy as np

#this generates a .vtk file that contains a vector field with vx = 0.5, vy = vz = 0
#on a grid that is on the Y = 0 plane
#
#use this to create the 0.5c velocity annotation by running a still with a specific view setting
#with 
#   PlotVelCustom=1  
#   VelCustomFile=$root/h5data/half_c_field.vtk
#where the customVel File is generated by this script
#make sure the view has the form where viewNormal = (0, y, z) or (0, -y, z) so that the arrows are orthogonal to the view


x_bdry = 300
x_N = 10
z_bdry = 300
z_N = 10
x_pts = np.linspace(-x_bdry, x_bdry, x_N)
z_pts = np.linspace(-z_bdry, z_bdry, z_N)

XX, ZZ = np.meshgrid(x_pts, z_pts, indexing='ij')
X = XX.flatten(); Z = ZZ.flatten()
N = x_N*z_N


header1 = "# vtk DataFile Version 2.0\nhalf_c_field\nASCII\nDATASET UNSTRUCTURED_GRID\nPOINTS {} float\n".format(N)
out_f = open("half_c_field.vtk", "w")
out_f.write(header1)
for i in range(N):
    Y = 0
    out_f.write("{} {} {}\n".format(X[i], Y, Z[i]))
header2 = "POINT_DATA {}\nVECTORS test float\n".format(N)
out_f.write(header2)
for i in range(N):
    out_f.write("{} {} {}\n".format(0.5, 0., 0.))
out_f.close()